const http = require('http');
const fs = require('fs');
const path = require('path');

const API_BASE = 'http://localhost:8888/api';
const BACKUP_FILE = path.join(__dirname, 'rules_backup.json');

const args = process.argv.slice(2);
const mode = args[0];

if (mode !== 'backup' && mode !== 'restore') {
    console.error('Usage: node rule_manager.js [backup|restore]');
    process.exit(1);
}

function makeRequest(url, method = 'GET', data = null) {
    return new Promise((resolve, reject) => {
        const urlObj = new URL(url);
        const options = {
            hostname: urlObj.hostname,
            port: urlObj.port,
            path: urlObj.pathname + urlObj.search,
            method: method,
            headers: {
                'Content-Type': 'application/json',
            },
        };

        const req = http.request(options, (res) => {
            let body = '';
            res.on('data', (chunk) => {
                body += chunk;
            });
            res.on('end', () => {
                if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                        resolve(body ? JSON.parse(body) : {});
                    } catch (e) {
                        resolve(body);
                    }
                } else {
                    reject(new Error(`Request failed with status ${res.statusCode}: ${body}`));
                }
            });
        });

        req.on('error', (e) => {
            reject(new Error(`Network error: ${e.message}`));
        });

        if (data) {
            req.write(JSON.stringify(data));
        }
        req.end();
    });
}

async function backup() {
    try {
        console.log('Fetching rules from EPGStation...');
        const response = await makeRequest(`${API_BASE}/rules?isHalfWidth=false&offset=0&limit=1000`);
        const rules = response.rules || [];

        if (rules.length === 0) {
            console.log('No rules found to backup or API returned empty.');
            return;
        }

        console.log(`Found ${rules.length} rules. Saving to ${BACKUP_FILE}...`);
        fs.writeFileSync(BACKUP_FILE, JSON.stringify(rules, null, 2), 'utf8');
        console.log('Backup successful!');
    } catch (err) {
        console.error('Error during backup:', err.message);
        console.log('Make sure EPGStation is running on localhost:8888');
    }
}

async function restore() {
    if (!fs.existsSync(BACKUP_FILE)) {
        console.error(`Backup file not found at ${BACKUP_FILE}. Please run backup first.`);
        process.exit(1);
    }

    try {
        console.log(`Reading rules from ${BACKUP_FILE}...`);
        const rules = JSON.parse(fs.readFileSync(BACKUP_FILE, 'utf8'));

        if (rules.length === 0) {
            console.log('No rules found in backup file.');
            return;
        }

        console.log(`Starting restore of ${rules.length} rules...`);
        let successCount = 0;
        let failCount = 0;

        for (const rule of rules) {
            try {
                // Strip out fields that are auto-generated by the backend (id, reserves, etc.)
                const payload = {
                    isTimeSpecification: rule.isTimeSpecification,
                    searchOption: rule.searchOption,
                    reserveOption: rule.reserveOption,
                    saveOption: rule.saveOption,
                    encodeOption: rule.encodeOption
                };

                await makeRequest(`${API_BASE}/rules`, 'POST', payload);
                successCount++;
                console.log(`Restored rule: ${rule.searchOption ? rule.searchOption.keyword : 'Time specified rule'}`);
            } catch (err) {
                failCount++;
                console.error(`Failed to restore rule (Keyword: ${rule.searchOption ? rule.searchOption.keyword : 'N/A'}):`, err.message);
            }
        }

        console.log(`Restore complete. Success: ${successCount}, Failed: ${failCount}`);
    } catch (err) {
        console.error('Error during restore:', err.message);
    }
}

if (mode === 'backup') {
    backup();
} else if (mode === 'restore') {
    restore();
}
